
services:
  enclave:
    build:
      context: .
      target: enclave-image
    environment:
      - PGHOST=db
    ports:
      - 3000:3000
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/0.0.0.0/3000; exit $?;'"
      interval: 5s
      timeout: 5s
      retries: 5
  da:
    build:
      context: .
      target: DA
    environment:
      - PGHOST=db
    depends_on:
      enclave:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=networkstates

    expose:
      - 5432
  client:
    build:
      context: .
      target: client
    environment:
      - PGHOST=db
    depends_on:
      enclave:
        condition: service_healthy