// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout, FieldLayoutLib } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { RESOURCE_TABLE, RESOURCE_OFFCHAIN_TABLE } from "@latticexyz/store/src/storeResourceTypes.sol";

ResourceId constant _tableId = ResourceId.wrap(
  bytes32(abi.encodePacked(RESOURCE_TABLE, bytes14(""), bytes16("Config")))
);
ResourceId constant ConfigTableId = _tableId;

FieldLayout constant _fieldLayout = FieldLayout.wrap(
  0x006c050014142004200000000000000000000000000000000000000000000000
);

struct ConfigData {
  address enclave;
  address verifierContract;
  uint256 numBlocksInInterval;
  uint32 numStartingTroops;
  uint256 claimedMoveLifeSpan;
}

library Config {
  /**
   * @notice Get the table values' field layout.
   * @return _fieldLayout The field layout for the table.
   */
  function getFieldLayout() internal pure returns (FieldLayout) {
    return _fieldLayout;
  }

  /**
   * @notice Get the table's key schema.
   * @return _keySchema The key schema for the table.
   */
  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _keySchema = new SchemaType[](0);

    return SchemaLib.encode(_keySchema);
  }

  /**
   * @notice Get the table's value schema.
   * @return _valueSchema The value schema for the table.
   */
  function getValueSchema() internal pure returns (Schema) {
    SchemaType[] memory _valueSchema = new SchemaType[](5);
    _valueSchema[0] = SchemaType.ADDRESS;
    _valueSchema[1] = SchemaType.ADDRESS;
    _valueSchema[2] = SchemaType.UINT256;
    _valueSchema[3] = SchemaType.UINT32;
    _valueSchema[4] = SchemaType.UINT256;

    return SchemaLib.encode(_valueSchema);
  }

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](0);
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](5);
    fieldNames[0] = "enclave";
    fieldNames[1] = "verifierContract";
    fieldNames[2] = "numBlocksInInterval";
    fieldNames[3] = "numStartingTroops";
    fieldNames[4] = "claimedMoveLifeSpan";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config (using the specified store).
   */
  function register(IStore _store) internal {
    _store.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get enclave.
   */
  function getEnclave() internal view returns (address enclave) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get enclave.
   */
  function _getEnclave() internal view returns (address enclave) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get enclave (using the specified store).
   */
  function getEnclave(IStore _store) internal view returns (address enclave) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = _store.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set enclave.
   */
  function setEnclave(address enclave) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((enclave)), _fieldLayout);
  }

  /**
   * @notice Set enclave.
   */
  function _setEnclave(address enclave) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((enclave)), _fieldLayout);
  }

  /**
   * @notice Set enclave (using the specified store).
   */
  function setEnclave(IStore _store, address enclave) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    _store.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((enclave)), _fieldLayout);
  }

  /**
   * @notice Get verifierContract.
   */
  function getVerifierContract() internal view returns (address verifierContract) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get verifierContract.
   */
  function _getVerifierContract() internal view returns (address verifierContract) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get verifierContract (using the specified store).
   */
  function getVerifierContract(IStore _store) internal view returns (address verifierContract) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = _store.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set verifierContract.
   */
  function setVerifierContract(address verifierContract) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((verifierContract)), _fieldLayout);
  }

  /**
   * @notice Set verifierContract.
   */
  function _setVerifierContract(address verifierContract) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((verifierContract)), _fieldLayout);
  }

  /**
   * @notice Set verifierContract (using the specified store).
   */
  function setVerifierContract(IStore _store, address verifierContract) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    _store.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((verifierContract)), _fieldLayout);
  }

  /**
   * @notice Get numBlocksInInterval.
   */
  function getNumBlocksInInterval() internal view returns (uint256 numBlocksInInterval) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get numBlocksInInterval.
   */
  function _getNumBlocksInInterval() internal view returns (uint256 numBlocksInInterval) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get numBlocksInInterval (using the specified store).
   */
  function getNumBlocksInInterval(IStore _store) internal view returns (uint256 numBlocksInInterval) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = _store.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set numBlocksInInterval.
   */
  function setNumBlocksInInterval(uint256 numBlocksInInterval) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((numBlocksInInterval)), _fieldLayout);
  }

  /**
   * @notice Set numBlocksInInterval.
   */
  function _setNumBlocksInInterval(uint256 numBlocksInInterval) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((numBlocksInInterval)), _fieldLayout);
  }

  /**
   * @notice Set numBlocksInInterval (using the specified store).
   */
  function setNumBlocksInInterval(IStore _store, uint256 numBlocksInInterval) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    _store.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((numBlocksInInterval)), _fieldLayout);
  }

  /**
   * @notice Get numStartingTroops.
   */
  function getNumStartingTroops() internal view returns (uint32 numStartingTroops) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get numStartingTroops.
   */
  function _getNumStartingTroops() internal view returns (uint32 numStartingTroops) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get numStartingTroops (using the specified store).
   */
  function getNumStartingTroops(IStore _store) internal view returns (uint32 numStartingTroops) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = _store.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set numStartingTroops.
   */
  function setNumStartingTroops(uint32 numStartingTroops) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((numStartingTroops)), _fieldLayout);
  }

  /**
   * @notice Set numStartingTroops.
   */
  function _setNumStartingTroops(uint32 numStartingTroops) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((numStartingTroops)), _fieldLayout);
  }

  /**
   * @notice Set numStartingTroops (using the specified store).
   */
  function setNumStartingTroops(IStore _store, uint32 numStartingTroops) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    _store.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((numStartingTroops)), _fieldLayout);
  }

  /**
   * @notice Get claimedMoveLifeSpan.
   */
  function getClaimedMoveLifeSpan() internal view returns (uint256 claimedMoveLifeSpan) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get claimedMoveLifeSpan.
   */
  function _getClaimedMoveLifeSpan() internal view returns (uint256 claimedMoveLifeSpan) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get claimedMoveLifeSpan (using the specified store).
   */
  function getClaimedMoveLifeSpan(IStore _store) internal view returns (uint256 claimedMoveLifeSpan) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = _store.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set claimedMoveLifeSpan.
   */
  function setClaimedMoveLifeSpan(uint256 claimedMoveLifeSpan) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((claimedMoveLifeSpan)), _fieldLayout);
  }

  /**
   * @notice Set claimedMoveLifeSpan.
   */
  function _setClaimedMoveLifeSpan(uint256 claimedMoveLifeSpan) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((claimedMoveLifeSpan)), _fieldLayout);
  }

  /**
   * @notice Set claimedMoveLifeSpan (using the specified store).
   */
  function setClaimedMoveLifeSpan(IStore _store, uint256 claimedMoveLifeSpan) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    _store.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((claimedMoveLifeSpan)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get() internal view returns (ConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, PackedCounter _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get() internal view returns (ConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, PackedCounter _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data (using the specified store).
   */
  function get(IStore _store) internal view returns (ConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, PackedCounter _encodedLengths, bytes memory _dynamicData) = _store.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    address enclave,
    address verifierContract,
    uint256 numBlocksInInterval,
    uint32 numStartingTroops,
    uint256 claimedMoveLifeSpan
  ) internal {
    bytes memory _staticData = encodeStatic(
      enclave,
      verifierContract,
      numBlocksInInterval,
      numStartingTroops,
      claimedMoveLifeSpan
    );

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    address enclave,
    address verifierContract,
    uint256 numBlocksInInterval,
    uint32 numStartingTroops,
    uint256 claimedMoveLifeSpan
  ) internal {
    bytes memory _staticData = encodeStatic(
      enclave,
      verifierContract,
      numBlocksInInterval,
      numStartingTroops,
      claimedMoveLifeSpan
    );

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using individual values (using the specified store).
   */
  function set(
    IStore _store,
    address enclave,
    address verifierContract,
    uint256 numBlocksInInterval,
    uint32 numStartingTroops,
    uint256 claimedMoveLifeSpan
  ) internal {
    bytes memory _staticData = encodeStatic(
      enclave,
      verifierContract,
      numBlocksInInterval,
      numStartingTroops,
      claimedMoveLifeSpan
    );

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    _store.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(ConfigData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.enclave,
      _table.verifierContract,
      _table.numBlocksInInterval,
      _table.numStartingTroops,
      _table.claimedMoveLifeSpan
    );

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(ConfigData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.enclave,
      _table.verifierContract,
      _table.numBlocksInInterval,
      _table.numStartingTroops,
      _table.claimedMoveLifeSpan
    );

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct (using the specified store).
   */
  function set(IStore _store, ConfigData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.enclave,
      _table.verifierContract,
      _table.numBlocksInInterval,
      _table.numStartingTroops,
      _table.claimedMoveLifeSpan
    );

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    _store.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      address enclave,
      address verifierContract,
      uint256 numBlocksInInterval,
      uint32 numStartingTroops,
      uint256 claimedMoveLifeSpan
    )
  {
    enclave = (address(Bytes.slice20(_blob, 0)));

    verifierContract = (address(Bytes.slice20(_blob, 20)));

    numBlocksInInterval = (uint256(Bytes.slice32(_blob, 40)));

    numStartingTroops = (uint32(Bytes.slice4(_blob, 72)));

    claimedMoveLifeSpan = (uint256(Bytes.slice32(_blob, 76)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    PackedCounter,
    bytes memory
  ) internal pure returns (ConfigData memory _table) {
    (
      _table.enclave,
      _table.verifierContract,
      _table.numBlocksInInterval,
      _table.numStartingTroops,
      _table.claimedMoveLifeSpan
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Delete all data for given keys (using the specified store).
   */
  function deleteRecord(IStore _store) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    _store.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    address enclave,
    address verifierContract,
    uint256 numBlocksInInterval,
    uint32 numStartingTroops,
    uint256 claimedMoveLifeSpan
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(enclave, verifierContract, numBlocksInInterval, numStartingTroops, claimedMoveLifeSpan);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dyanmic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    address enclave,
    address verifierContract,
    uint256 numBlocksInInterval,
    uint32 numStartingTroops,
    uint256 claimedMoveLifeSpan
  ) internal pure returns (bytes memory, PackedCounter, bytes memory) {
    bytes memory _staticData = encodeStatic(
      enclave,
      verifierContract,
      numBlocksInInterval,
      numStartingTroops,
      claimedMoveLifeSpan
    );

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple() internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    return _keyTuple;
  }
}
