// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { SpawnInputs } from "common/SpawnInputs.sol";
import { Groth16Proof } from "common/Groth16Proof.sol";
import { VirtualInputs } from "common/VirtualInputs.sol";
import { Signature } from "common/Signature.sol";

/**
 * @title ISpawnSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ISpawnSystem {
  function commitToSpawn(uint256 h) external;

  function spawn(
    SpawnInputs memory spawnInputs,
    Groth16Proof memory spawnProof,
    VirtualInputs memory virtualInputs,
    Groth16Proof memory virtualProof,
    Signature memory sig
  ) external;

  function set(uint256 h) external;

  function getSpawnCommitment(address player) external view returns (uint256);

  function getSpawnblindHash(address player) external view returns (uint256);

  function getBlockHash(uint256 blockCommited) external view returns (uint256);
}
