// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */
enum Direction {
  UP,
  DOWN,
  LEFT,
  RIGHT
}

enum Terrain {
  BARE,
  MOUNTAIN,
  WATER
}

enum Bonus {
  NONE,
  TROOP
}
