// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Config, ConfigData, ConfigTableId } from "./tables/Config.sol";
import { SpawnCommitment, SpawnCommitmentTableId } from "./tables/SpawnCommitment.sol";
import { SpawnChallengeHash, SpawnChallengeHashTableId } from "./tables/SpawnChallengeHash.sol";
import { TileCommitment, TileCommitmentTableId } from "./tables/TileCommitment.sol";
import { CityTroopCount, CityTroopCountTableId } from "./tables/CityTroopCount.sol";
import { CityCenterTroopCount, CityCenterTroopCountTableId } from "./tables/CityCenterTroopCount.sol";
import { CityArea, CityAreaTableId } from "./tables/CityArea.sol";
import { CityPlayer, CityPlayerTableId } from "./tables/CityPlayer.sol";
import { PlayerLastUpdateBlock, PlayerLastUpdateBlockTableId } from "./tables/PlayerLastUpdateBlock.sol";
