// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Config, ConfigData, ConfigTableId } from "./tables/Config.sol";
import { SpawnCommitment, SpawnCommitmentTableId } from "./tables/SpawnCommitment.sol";
import { TileCommitment, TileCommitmentTableId } from "./tables/TileCommitment.sol";
import { ConsumedCommitment, ConsumedCommitmentTableId } from "./tables/ConsumedCommitment.sol";
import { City, CityData, CityTableId } from "./tables/City.sol";
import { CityPlayer, CityPlayerTableId } from "./tables/CityPlayer.sol";
import { PlayerLastUpdateBlock, PlayerLastUpdateBlockTableId } from "./tables/PlayerLastUpdateBlock.sol";
